import Foundation

/// The daily morning brief — the core output of the product.
/// Generated by: Rule Engine (judgment) → AI (natural language translation).
struct DailyBrief: Identifiable, Codable {
    let id: UUID
    let date: String  // Calendar day: "2026-07-31"
    let generatedAt: Date

    // --- Rule Engine Outputs ---
    /// Per-metric trend results
    let metricTrends: [TrendResult]
    /// Signal/noise classification for each metric shown
    let classifications: [SignalNoiseVerdict]
    /// The user's most recent feeling log
    let latestFeeling: FeelLog?
    /// Any conflicts that were resolved
    let conflictVerdict: ConflictVerdict?
    /// Active ignore count
    let ignoreCount: Int

    // --- AI Translation Output ---
    /// The natural-language brief text (LLM-generated, based on rule engine output)
    let briefText: String
    /// One-line takeaway
    let takeaway: String

    init(date: String = Date().dayKey(),
         metricTrends: [TrendResult],
         classifications: [SignalNoiseVerdict],
         latestFeeling: FeelLog? = nil,
         conflictVerdict: ConflictVerdict? = nil,
         ignoreCount: Int = 0,
         briefText: String,
         takeaway: String) {
        self.id = UUID()
        self.date = date
        self.generatedAt = Date()
        self.metricTrends = metricTrends
        self.classifications = classifications
        self.latestFeeling = latestFeeling
        self.conflictVerdict = conflictVerdict
        self.ignoreCount = ignoreCount
        self.briefText = briefText
        self.takeaway = takeaway
    }

    // MARK: - Template brief (offline fallback - no AI needed)

    /// Generate a template brief using ONLY rule engine output.
    /// This is the fallback when the AI API is unavailable.
    /// Every line is deterministic and explainable.
    static func templateBrief(from trends: [TrendResult],
                              classifications: [SignalNoiseVerdict],
                              conflictVerdict: ConflictVerdict?,
                              userGoal: UserGoal) -> DailyBrief {
        var lines: [String] = ["☀️ \(Date().formatted(date: .long, time: .omitted)) Morning Brief\n"]

        // Per-metric: trend direction + signal/noise verdict
        for trend in trends {
            let classification = classifications.first(where: { $0.metric == trend.metric })
            let noiseFlag = classification?.classification == .noise ? " [ignore — noise]" : ""
            let anomalyFlag = trend.isTrendAnomaly ? " ⚠️ trend anomaly" : ""

            if let mean = trend.sevenDayMean {
                lines.append("• \(trend.metric.displayName): 7d avg \(String(format: "%.1f", mean)) \(trend.metric.unit) — \(trend.direction.displayName)\(noiseFlag)\(anomalyFlag)")
            }
        }

        // Conflict resolution (if any)
        if let conflict = conflictVerdict {
            lines.append("\n⚖️ Feel vs Score: \(conflict.advice)")
        }

        // Takeaway
        lines.append("\n💡 Takeaway: \(generateTakeaway(trends: trends, goal: userGoal))")

        let briefText = lines.joined(separator: "\n")

        return DailyBrief(
            date: Date().dayKey(),
            metricTrends: trends,
            classifications: classifications,
            conflictVerdict: conflictVerdict,
            briefText: briefText,
            takeaway: generateTakeaway(trends: trends, goal: userGoal)
        )
    }

    private static func generateTakeaway(trends: [TrendResult], goal: UserGoal) -> String {
        let anomalies = trends.filter(\.isTrendAnomaly)
        let changes = trends.filter { $0.direction.isChange }

        if anomalies.isEmpty && changes.isEmpty {
            return "Everything is stable. Keep doing what you're doing. ✨"
        }

        if !anomalies.isEmpty {
            let names = anomalies.map(\.metric.displayName).joined(separator: ", ")
            return "Heads up: \(names) show trend-level changes. Worth watching this week."
        }

        let summary = changes.prefix(2).map { "\($0.metric.displayName) \($0.direction.displayName.lowercased())" }.joined(separator: ", ")
        return "Notable: \(summary). The rest is stable. No action needed."
    }
}

// MARK: - Date Helpers

extension Date {
    func dayKey() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: self)
    }
}
